# ESLint config
# http://eslint.org/

env:
  node: true
  browser: true
  jquery: true
  es6: true

rules:
  strict:
    - 0

  comma-dangle:
    - 2
    - never

  indent:
    - 2
    - 2

  quotes:
    - 2
    - single

  brace-style:
    - 1
    - 1tbs

  semi:
    - 2
    - always

  linebreak-style:
    - 2
    - unix

  one-var:
    - 1
    - never

  comma-style:
    - 1
    - last

  curly: 2

  eqeqeq:
    - 2
    - allow-null

  key-spacing:
    - 1
    -
      beforeColon: false
      afterColon: true

  comma-spacing:
    - 1
    -
      before: false
      after: true

  space-before-blocks:
    - 1
    - always

  space-in-parens:
    - 1
    - never

  space-before-function-paren:
    - 1
    - never

  no-trailing-spaces: 1

  keyword-spacing:
    - 2
    -
      before: true
      after: true
